In [46]:
import Keypoints
import numpy as np
import tensorflow.keras as keras
from tensorflow.keras import layers
import random

In [47]:
seed = [*range(15)]
random.shuffle(seed)
label = np.array([i for i in range(3) for _ in range(5)])
label = np.array(label[seed])
print(label)
cnt = 0
r = ['D', 'F', 'L', 'R', 'U']
li = np.array([])

[2 2 2 1 2 0 1 1 1 0 0 0 1 0 2]


In [49]:
for k in [1, 6, 28]:
    for i in r:
        cnt += 1
        a, b, c = map(np.array, Keypoints.getkey_from_vid(f'./원시데이터/NIA_SL_SEN000{k}_REAL01_{i}.mp4'))
        print(f"Data Loading... {cnt}/{15}")
        data = np.concatenate([a, b, c], axis=1)
        data = np.array([data[-10:-5][:]])
        if i == 'D' and k == 1:
            li = data
        else:
            li = np.vstack([li, data])
li = np.array(li[seed])

Data Loading... 12/15
Data Loading... 13/15
Data Loading... 14/15
Data Loading... 15/15
Data Loading... 16/15
Data Loading... 17/15
Data Loading... 18/15
Data Loading... 19/15
Data Loading... 20/15
Data Loading... 21/15
Data Loading... 22/15
Data Loading... 23/15
Data Loading... 24/15
Data Loading... 25/15
Data Loading... 26/15


In [50]:
li.shape

(15, 5, 167)

In [51]:
model = keras.Sequential()
model.add(layers.GRU(256, return_sequences=True))
model.add(layers.SimpleRNN(128))
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dropout(0.1))
model.add(layers.Dense(3, activation='softmax'))
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['acc'])
model.fit(li, label, epochs=100)
model.save("SecondGru.h5")

Epoch 1/100
1/1 [==============================] - 2s 2s/step - loss: 1.0934 - acc: 0.3333
Epoch 2/100
1/1 [==============================] - 0s 5ms/step - loss: 1.0432 - acc: 0.3333
Epoch 3/100
1/1 [==============================] - 0s 5ms/step - loss: 0.9898 - acc: 0.4000
Epoch 4/100
1/1 [==============================] - 0s 5ms/step - loss: 0.9080 - acc: 0.5333
Epoch 5/100
1/1 [==============================] - 0s 6ms/step - loss: 0.8365 - acc: 0.6667
Epoch 6/100
1/1 [==============================] - 0s 5ms/step - loss: 0.7746 - acc: 0.7333
Epoch 7/100
1/1 [==============================] - 0s 5ms/step - loss: 0.6563 - acc: 0.7333
Epoch 8/100
1/1 [==============================] - 0s 5ms/step - loss: 0.5766 - acc: 0.8000
Epoch 9/100
1/1 [==============================] - 0s 6ms/step - loss: 0.5100 - acc: 0.8000
Epoch 10/100
1/1 [==============================] - 0s 6ms/step - loss: 0.4402 - acc: 0.9333
Epoch 11/100
1/1 [==============================] - 0s 4ms/step - loss: 0.3439 -

In [53]:
a, b, c = map(np.array, Keypoints.getkey_from_cam())
data = np.concatenate([a, b, c], axis=1)
data = np.array([data[-10:-5][:]])
data.shape

127
20
20


(1, 5, 167)

(167,)

In [20]:
import cv2

for i in range(5):
    cv2.imshow("1", data[0][i])
    cv2.waitKey()
    cv2.destroyAllWindows()

In [54]:
model.predict(data)

array([[9.9564254e-01, 4.3571130e-03, 3.6100619e-07]], dtype=float32)

In [56]:
a, b, c = map(np.array, Keypoints.getkey_from_cam())
test_2 = np.concatenate([a, b, c], axis=1)

127
20
20


In [57]:
test_data = np.array([test_2[-10:-5][:]])

In [60]:
test_data = np.array([test_2[-15:-10][:]])
test_data.shape

(1, 5, 167)

In [61]:
model.predict(test_data)

array([[9.9991834e-01, 8.1593666e-05, 3.0518663e-08]], dtype=float32)

In [41]:
a, b, c = map(np.array, Keypoints.getkey_from_cam())
test_3 = np.concatenate([a, b, c], axis=1)

127
20
20


In [43]:
test_3_final = np.array([test_3[-10:-5][:]])

In [44]:
test_3_final.shape

(1, 5, 167)

In [45]:
model.predict(test_3_final)

array([[9.9997377e-01, 2.6079653e-05, 1.4107437e-07]], dtype=float32)

In [63]:
done = False
cnt = 1
while not done:
    if cnt % 5 == 0:
        a, b, c = map(np.array, Keypoints.getkey_from_cam())
        test = np.concatenate([a, b, c], axis=1)
        test_out = np.array(test[-5:][:])
        print(model.predict(test_out))
    cnt += 1

127
20
20


ValueError: in user code:

    File "/usr/lib/python3.9/site-packages/keras/engine/training.py", line 1621, in predict_function  *
        return step_function(self, iterator)
    File "/usr/lib/python3.9/site-packages/keras/engine/training.py", line 1611, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/usr/lib/python3.9/site-packages/keras/engine/training.py", line 1604, in run_step  **
        outputs = model.predict_step(data)
    File "/usr/lib/python3.9/site-packages/keras/engine/training.py", line 1572, in predict_step
        return self(x, training=False)
    File "/usr/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "/usr/lib/python3.9/site-packages/keras/engine/input_spec.py", line 213, in assert_input_compatibility
        raise ValueError(f'Input {input_index} of layer "{layer_name}" '

    ValueError: Exception encountered when calling layer "sequential_4" (type Sequential).
    
    Input 0 of layer "gru_4" is incompatible with the layer: expected ndim=3, found ndim=2. Full shape received: (None, 167)
    
    Call arguments received:
      • inputs=tf.Tensor(shape=(None, 167), dtype=float32)
      • training=False
      • mask=None
